# 2025/8/13

In [1]:
import pandas as pd
# pd.set_option('display.max_rows', 10) # 指定最大的"列數"
# pd.set_option('display.max_columns', 10) # 指定最大的"行數"
# pd.options.display.max_columns= None #直接指定顯示所有的"行"
# pd.options.display.max_rows= None #直接指定顯示所有的"列"
df = pd.DataFrame(
{"a" : [4, 5, 6],
"b" : [7, 8, 9],
"c" : [10, 11, 12]},
index = [1, 2, 3])
df

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [2]:
df = pd.DataFrame(
            [[4, 5, 6],
             [7, 8, 9],
             [10, 11, 12]],
             index = [101, 102, 103],
             columns=['a','b','c'])
df

      a   b   c
101   4   5   6
102   7   8   9
103  10  11  12

In [3]:
d = {'a': 1, 'b': 2, 'c': 3}
ser = pd.Series(data=d)
ser

a    1
b    2
c    3
dtype: int64

In [4]:
df = pd.DataFrame()
ser = pd.Series()
df
ser

Series([], dtype: object)

In [5]:
# 字串解析並存入字典結構 轉成DF

import datetime

f = open('學生資料表.txt', 'r', encoding="UTF-8")
data_string = f.read() # 變成一個很大的字串
f.close()

# 利用跳行轉義字符\n切割字串
lines = data_string.split('\n')

students = {}
姓名 = []
學號  = []
成績一 =  []
成績二 =  []
生日 = []

for line in lines:
    if line.strip():  # 如果是空行就跳過
        parts = line.split()
        姓名.append(parts[0])
        學號.append(parts[1])
        成績一.append(int(parts[2]))
        成績二.append(int(parts[3]))
        生日.append(parts[4])

        
students['姓名'] = 姓名
students['學號'] = 學號
students['成績一']  = 成績一
students['成績二'] = 成績二
students['生日'] = 生日

df = pd.DataFrame(students)
df

     姓名  學號  成績一  成績二          生日
0   林治宏  01   75   87  1998/05/22
1   陳建偉  02   60   78  2005/08/19
2   鍾祖培  03   61   51  2001/01/05
3   鄭榮仁  04   97   83  1997/09/03
4   廖天珩  05   75   75  2002/09/15
5   宋立群  06   75   70  2003/08/02
6   呂文凱  07   67   64  2003/12/21
7   吳采曄  08   50   96  1996/08/25
8   方品絨  09   94   82  1996/02/25
9   李界寬  10   69   81  1997/06/11
10  古智誠  11  100   98  2001/09/03
11  吳辰桀  12   91   60  1996/11/05
12  楊尚謙  13   54   67  2003/02/06
13  范佐謙  14   62   59  1997/09/16
14  沈柏臻  15   87   97  2002/10/01
15  陳恩生  16   53   90  2005/11/21
16  徐豪岑  17   76   63  2004/09/25
17  王彥傑  18   76   51  2000/05/24
18  彭瑋翊  19   96   77  1999/07/13
19  周哲民  20   92   92  1998/05/12
20  陳邑溓  21   75   87  2001/11/24
21  姜冠宏  22   72   71  1996/03/08
22  彭明偉  23   71   79  2003/12/24
23  詹昇諭  24   78   84  1995/02/08
24  陳家慶  25   91   70  2000/03/06
25  劉凡綺  26   50   56  2000/12/26
26  黃連豐  27   52   70  2002/01/09
27  古文晴  28   50   77  2000/09/19
28  王文鴻  29   65   60  1995/12/07
29  古家宇  30   69   73  1997/11/03
30   蘇有  31   52   65  2002/01/21

In [6]:
# 字串解析並存入串列結構 轉成DF
import datetime
f = open('學生資料表.txt', 'r', encoding="UTF-8")
data_string = f.read()
f.close()


# 分割字符串為行
lines = data_string.split('\n')

# 創建學生列表（每筆資料是一個子列表）
students = []

for line in lines:
    if line.strip():  # 確保行不為空
        parts = line.split()
        # 將每行數據轉換為列表並添加到students中
        student = [
            parts[0],       # 姓名
            parts[1],       # 學號
            int(parts[2]),   # 成績一
            int(parts[3]),   # 成績二
            parts[4]        # 生日
        ]
        students.append(student)

df = pd.DataFrame(students,columns=['姓名','學號','成績一','成績二','生日'])
# 動態新增欄位
df['平均'] = (df['成績一'] + df['成績二'])/2
# 依平均成績排序，平均高的名次小
df['名次'] = df['平均'].rank(ascending=False, method='dense').astype(int)

def 評價等級函數 (x):
    if x >= 90:return 'A'
    elif x >= 80:return 'B'
    elif x >= 70:return 'C'
    elif x >= 60:return 'D'
    else:return 'E'
        
# 新增等級欄位
df['等級'] = df['平均'].apply(評價等級函數)

import datetime
def 年齡計算 (y):
    
    # step1. 把生日字串變成日期結構  'strftime'日期變字串, 'strptime'字串變日期
    我的生日 = datetime.datetime.strptime(y,'%Y/%m/%d')
    
    # step2. 得到今天日期結構
    今天日期 = datetime.datetime.now()
    
    # step3. 算年齡
    age = 今天日期.year - 我的生日.year
    
    # step4. 如果生日還沒過  年齡要減一
    if 今天日期 < datetime.datetime(今天日期.year,我的生日.month,我的生日.day) :
        age -= 1
        
    return age
# 新增年齡欄位
df['年齡'] = df['生日'].apply(年齡計算)
df

     姓名  學號  成績一  成績二          生日    平均  名次 等級  年齡
0   林治宏  01   75   87  1998/05/22  81.0   6  B  27
1   陳建偉  02   60   78  2005/08/19  69.0  15  D  20
2   鍾祖培  03   61   51  2001/01/05  56.0  22  E  24
3   鄭榮仁  04   97   83  1997/09/03  90.0   3  A  27
4   廖天珩  05   75   75  2002/09/15  75.0   9  C  22
5   宋立群  06   75   70  2003/08/02  72.5  11  C  22
6   呂文凱  07   67   64  2003/12/21  65.5  16  D  21
7   吳采曄  08   50   96  1996/08/25  73.0  10  C  28
8   方品絨  09   94   82  1996/02/25  88.0   4  B  29
9   李界寬  10   69   81  1997/06/11  75.0   9  C  28
10  古智誠  11  100   98  2001/09/03  99.0   1  A  23
11  吳辰桀  12   91   60  1996/11/05  75.5   8  C  28
12  楊尚謙  13   54   67  2003/02/06  60.5  20  D  22
13  范佐謙  14   62   59  1997/09/16  60.5  20  D  27
14  沈柏臻  15   87   97  2002/10/01  92.0   2  A  22
15  陳恩生  16   53   90  2005/11/21  71.5  12  C  19
16  徐豪岑  17   76   63  2004/09/25  69.5  14  D  20
17  王彥傑  18   76   51  2000/05/24  63.5  17  D  25
18  彭瑋翊  19   96   77  1999/07/13  86.5   5  B  26
19  周哲民  20   92   92  1998/05/12  92.0   2  A  27
20  陳邑溓  21   75   87  2001/11/24  81.0   6  B  23
21  姜冠宏  22   72   71  1996/03/08  71.5  12  C  29
22  彭明偉  23   71   79  2003/12/24  75.0   9  C  21
23  詹昇諭  24   78   84  1995/02/08  81.0   6  B  30
24  陳家慶  25   91   70  2000/03/06  80.5   7  B  25
25  劉凡綺  26   50   56  2000/12/26  53.0  23  E  24
26  黃連豐  27   52   70  2002/01/09  61.0  19  D  23
27  古文晴  28   50   77  2000/09/19  63.5  17  D  24
28  王文鴻  29   65   60  1995/12/07  62.5  18  D  29
29  古家宇  30   69   73  1997/11/03  71.0  13  C  27
30   蘇有  31   52   65  2002/01/21  58.5  21  E  23

In [7]:
# 字串解析並存入串列結構   最後轉成 DF

f = open('學生資料表.txt', 'r', encoding="UTF-8")
data_string = f.read()
f.close()

# 分割字符串為行
lines = data_string.split('\n')

# 創建學生列表（每筆資料是一個子列表）
students = []

for line in lines:
    if line.strip():  # 確保行不為空
        parts = line.split()
        # 將每行數據轉換為列表並添加到students中
        student = [
            parts[0],        # 姓名
            parts[1],        # 學號
            int(parts[2]),   # 成績一
            int(parts[3]),   # 成績二
            parts[4]         # 生日
        ]
        students.append(student)

df = pd.DataFrame( students, columns=['姓名','學號','成績一','成績二','生日'] )

df['姓名'] = df['姓名'].astype('string')
df['學號'] = df['學號'].astype('string')
df['生日'] = df['生日'].astype('datetime64[ns]')

# 使用 pandas 的向量運算計算年齡
today = pd.Timestamp.today()
df['年齡'] = today.year - df['生日'].dt.year - ( 
    (today.month < df['生日'].dt.month) | ((today.month == df['生日'].dt.month) & (today.day < df['生日'].dt.day))
    ).astype(int)

# 這樣做的好處：

# * 不需使用 `datetime.datetime` 模組，完全依賴 Pandas。
# * 計算方式是「向量化」，速度比 `apply()` 快很多，對大數據特別有效。
df

     姓名  學號  成績一  成績二         生日  年齡
0   林治宏  01   75   87 1998-05-22  27
1   陳建偉  02   60   78 2005-08-19  20
2   鍾祖培  03   61   51 2001-01-05  24
3   鄭榮仁  04   97   83 1997-09-03  27
4   廖天珩  05   75   75 2002-09-15  22
5   宋立群  06   75   70 2003-08-02  22
6   呂文凱  07   67   64 2003-12-21  21
7   吳采曄  08   50   96 1996-08-25  28
8   方品絨  09   94   82 1996-02-25  29
9   李界寬  10   69   81 1997-06-11  28
10  古智誠  11  100   98 2001-09-03  23
11  吳辰桀  12   91   60 1996-11-05  28
12  楊尚謙  13   54   67 2003-02-06  22
13  范佐謙  14   62   59 1997-09-16  27
14  沈柏臻  15   87   97 2002-10-01  22
15  陳恩生  16   53   90 2005-11-21  19
16  徐豪岑  17   76   63 2004-09-25  20
17  王彥傑  18   76   51 2000-05-24  25
18  彭瑋翊  19   96   77 1999-07-13  26
19  周哲民  20   92   92 1998-05-12  27
20  陳邑溓  21   75   87 2001-11-24  23
21  姜冠宏  22   72   71 1996-03-08  29
22  彭明偉  23   71   79 2003-12-24  21
23  詹昇諭  24   78   84 1995-02-08  30
24  陳家慶  25   91   70 2000-03-06  25
25  劉凡綺  26   50   56 2000-12-26  24
26  黃連豐  27   52   70 2002-01-09  23
27  古文晴  28   50   77 2000-09-19  24
28  王文鴻  29   65   60 1995-12-07  29
29  古家宇  30   69   73 1997-11-03  27
30   蘇有  31   52   65 2002-01-21  23